---
- name: assert example one
  hosts: all
  vars:
          - mylist:
                  - httpd
                  - firewalld
                  - openssh
  tasks:
          - name: check mylist value one
            assert:
                    that:
                            - mylist[0] == 'httpd'
