---
- name: find files starting with bash
  hosts: all
  gather_facts: false
  tasks:
          - name: using glob plugin
            debug:
                    msg: "{{ query('fileglob', '~/.bash*') }}"
