--
- name: lookup data in playbook
  hosts: all
  become: true
  gather_facts: false
  vars:
          mydata: "{{ lookup('file','/etc/passwd','/etc/issue') }}"
  tasks:
          - name: process data
            copy:
                    content: "{{ mydata }}"
                    dest: /tmp/lookupdata2.txt

          - name: cat /tmp/lookupdata2.txt
            command: 'cat /tmp/lookupdata2.txt'
            register: cat

          - name: debugging command
            debug:
                    var: cat
