---
- name: collect only network facts
  hosts: all
  tasks:
          - name: gathering only network facts
            setup:
                    gather_subset:
                            - network
            register: network

          - name: debug
            debug:
                    var: network
